# permissions for end users to view gitcds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitcd-viewer-role
rules:
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds/status
  verbs:
  - get
