# permissions for end users to edit gitcds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitcd-editor-role
rules:
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds/status
  verbs:
  - get
