
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds/finalizers
  verbs:
  - update
- apiGroups:
  - git.winlab.com
  resources:
  - gitcds/status
  verbs:
  - get
  - patch
  - update
